from app.config import get_settings
settings = get_settings()
print(f"MODEL: {settings.ollama_model}")
print(f"FAST: {settings.ollama_fast_model}")
print(f"REASONING: {settings.ollama_reasoning_model}")
print(f"THINK: {settings.ollama_think}")
print(f"NUM_CTX: {settings.ollama_num_ctx}")
print(f"NUM_PREDICT: {settings.ollama_num_predict}")
print(f"NUM_GPU: {settings.ollama_num_gpu}")
print(f"NUM_BATCH: {settings.ollama_num_batch}")
print(f"KEEP_ALIVE: {settings.ollama_keep_alive}")
